export const banks = [
  { name: "Agriwise", logo: "agriwise.webp" },
  //   { name: "All Bank", logo: "allbank.webp" },
  { name: "AU Small Finance Bank", logo: "Au.webp" },
  { name: "Bajaj", logo: "bajaj.webp" },
  { name: "Bajaj Ameriya Bank", logo: "bajaj.webp" },
  { name: "Chola", logo: "chola.webp" },
  { name: "DMI Finance", logo: "dmifinance.webp" },
  { name: "Federal Bank", logo: "fed.webp" },
  { name: "Hero Fincorp", logo: "hero.webp" },
  { name: "Home First", logo: "homefrist.webp" },
  { name: "Home First Trench", logo: "homefrist.webp" },
  { name: "ICICI", logo: "ici.webp" },
  { name: "ICICI HFC", logo: "ici.webp" },
  { name: "IDFC First Bank", logo: "idfc.webp" },
  { name: "Manappuram", logo: "manipuram.webp" },
  { name: "Piramal", logo: "pirmal.webp" },
  { name: "PiramalNPA Form", logo: "pirmal.webp" },
  { name: "Profectus", logo: "proefectus.webp" },
  { name: "Protium", logo: "protium.webp" },
  { name: "Aditya", logo: "aditya.webp" },
  { name: "Samasta", logo: "samsata.webp" },
  { name: "Shriram", logo: "shriram.webp" },
  { name: "Shubham", logo: "shubham.webp" },
  { name: "Sundaram", logo: "sundaram.webp" },
  { name: "Suryoday", logo: "suryoday.webp" },
  { name: "Utkarsh", logo: "utkarsh.webp" },
];
